# Generated by Django 3.0.3 on 2021-08-31 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_commentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.CommentImage'),
        ),
    ]
