# Generated by Django 3.0.3 on 2021-09-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0006_auto_20210901_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ManyToManyField(blank=True, to='calibration.CommentImage'),
        ),
    ]
