# Generated by Django 3.0.3 on 2021-09-11 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0009_auto_20210911_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='certificate_id2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.Certificate'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='group',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
