# Generated by Django 3.0.3 on 2021-09-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0011_remove_activity_certificate_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='group',
        ),
    ]
