# Generated by Django 3.0.3 on 2021-09-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0013_activity_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
