# Generated by Django 3.0.3 on 2021-09-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0015_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='group',
            field=models.CharField(max_length=255),
        ),
    ]
