# Generated by Django 3.0.3 on 2021-09-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0016_auto_20210911_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='certificate_id2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.Certificate'),
        ),
    ]
