# Generated by Django 3.0.3 on 2021-09-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0017_activity_certificate_id2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='certificate_id2',
            new_name='certificate',
        ),
    ]
