# Generated by Django 3.0.3 on 2023-03-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0018_auto_20210911_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_id2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
