# Generated by Django 3.0.3 on 2023-03-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0019_certificate_certificate_id2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(null=True)),
                ('cert_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ManyToManyField(blank=True, to='calibration.CommentImage')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
