# Generated by Django 3.0.3 on 2023-03-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0020_comment2'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='comments2',
            field=models.ManyToManyField(blank=True, to='calibration.Comment2'),
        ),
    ]
