# Generated by Django 3.0.3 on 2023-01-08 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='not set', max_length=100)),
                ('product_name', models.CharField(default='not set', max_length=255)),
                ('addcart_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(default='not set', max_length=100)),
                ('customer', models.CharField(default='not set', max_length=100)),
                ('comments', models.ManyToManyField(blank=True, to='shopee.Product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
