# Generated by Django 3.0.3 on 2023-01-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='comments',
            new_name='products',
        ),
    ]
