# Generated by Django 3.0.3 on 2023-01-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0002_auto_20230108_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='list',
        ),
    ]
