# Generated by Django 3.0.3 on 2023-01-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0004_auto_20230108_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='list',
        ),
        migrations.AddField(
            model_name='cart',
            name='list',
            field=models.ManyToManyField(blank=True, to='shopee.Product'),
        ),
    ]
