# Generated by Django 3.0.3 on 2023-01-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0005_auto_20230108_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(default='not set', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.CharField(default='not set', max_length=255),
        ),
    ]
