# Generated by Django 3.0.3 on 2021-01-13 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('ordered', models.BooleanField(default=False)),
                ('cartadded', models.BooleanField(default=False)),
                ('item_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('shipping_address', models.CharField(default='not set', max_length=100)),
                ('items', models.ManyToManyField(to='shopping.Item')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
