# Generated by Django 3.0.3 on 2021-01-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_item_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.Order'),
        ),
    ]
