# Generated by Django 3.0.3 on 2021-01-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20210114_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.CharField(default='not set', max_length=100),
        ),
    ]
