# Generated by Django 3.0.3 on 2021-01-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0002_fooditem_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(default='not set', max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(default='not set', max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.CharField(default='not set', max_length=100),
        ),
    ]
