# Generated by Django 3.0.3 on 2021-01-21 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0003_auto_20210121_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default='default.jpg', upload_to='upload_pics')),
            ],
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_delivery.FoodAvatar'),
        ),
    ]
