# Generated by Django 3.0.3 on 2021-01-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0005_auto_20210121_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodavatar',
            old_name='file',
            new_name='imagefile',
        ),
    ]
