# Generated by Django 3.0.3 on 2021-01-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0006_auto_20210121_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='avatar',
            field=models.CharField(default='not set', max_length=100),
        ),
    ]
