# Generated by Django 3.0.3 on 2021-01-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0007_auto_20210121_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_delivery.FoodAvatar'),
        ),
    ]
