# Generated by Django 3.0.3 on 2021-01-22 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_delivery', '0008_auto_20210121_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(default='not set', max_length=100)),
                ('state', models.CharField(default='not set', max_length=100)),
                ('postal_code', models.CharField(default='not set', max_length=100)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addressorder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
