# Generated by Django 3.0.3 on 2021-01-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0010_auto_20210123_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='order_id',
            field=models.CharField(default='not set', max_length=100),
        ),
    ]
