# Generated by Django 3.0.3 on 2021-01-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0015_fakedata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesdata',
            options={'ordering': ['id']},
        ),
    ]
