# Generated by Django 3.0.3 on 2021-01-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0016_auto_20210129_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakedata',
            old_name='SalesData',
            new_name='salesData',
        ),
    ]
