# Generated by Django 3.0.3 on 2021-01-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0017_auto_20210129_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeData2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesData', models.ManyToManyField(to='food_delivery.SalesData')),
            ],
        ),
    ]
