# Generated by Django 3.0.3 on 2021-01-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0018_fakedata2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FakeData',
        ),
    ]
