# Generated by Django 3.0.3 on 2021-01-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0020_auto_20210129_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='y',
            field=models.IntegerField(default=100),
        ),
    ]
