# Generated by Django 3.0.3 on 2021-02-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobb', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='posts',
            field=models.ManyToManyField(to='djangobb.Post'),
        ),
    ]
