# Generated by Django 3.0.3 on 2021-02-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobb', '0003_topic_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='posts',
            field=models.ManyToManyField(blank=True, to='djangobb.Post'),
        ),
    ]
